---
- name: determine installed blackbox_exporter version
  shell: blackbox_exporter --version 2>&1 | awk '/blackbox_exporter, version/{print $3}'
  register: blackbox_exporter_version_output

- name: set blackbox_exporter_installed_version fact
  set_fact: blackbox_exporter_installed_version="{{blackbox_exporter_version_output.stdout}}"

- name: install blackbox_exporter
  shell: |
    cd `mktemp -d`
    curl -fsSLO https://github.com/prometheus/blackbox_exporter/releases/download/v{{blackbox_exporter_version}}/blackbox_exporter-{{blackbox_exporter_version}}.linux-amd64.tar.gz
    tar xvfz blackbox_exporter-{{blackbox_exporter_version}}.linux-amd64.tar.gz
    install -m 0755 blackbox_exporter-{{blackbox_exporter_version}}.linux-amd64/blackbox_exporter /usr/local/bin/blackbox_exporter
  when: blackbox_exporter_installed_version != blackbox_exporter_version
  notify: restart blackbox_exporter

- name: install blackbox_exporter config
  copy:
    src: "{{ blackbox_exporter_config }}"
    dest: /etc/prometheus/blackbox.yml
    owner: prometheus
    group: prometheus
    validate: blackbox_exporter --config.check --config.file %s
  notify: restart blackbox_exporter

- name: install blackbox_exporter.service
  copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service
  notify: restart blackbox_exporter

- name: enable blackbox_exporter.service
  systemd:
    name: blackbox_exporter
    enabled: true
