---
grafana_version: 9.0.7
grafana_home_dir: "/var/lib/grafana"
grafana_config_dir: "/etc/grafana"
grafana_config_path: "{{ grafana_config_dir }}/defaults.ini"
grafana_web_external_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
grafana_admin_user: "admin"
grafana_cookie_secure: true
grafana_dashboards_dir: ""
grafana_auto_assign_org_role: "Editor"
