---
prometheus_version: 2.33.4
prometheus_home_dir: "/var/lib/prometheus"
prometheus_data_dir: "{{ prometheus_home_dir }}/data"
prometheus_config_dir: "/etc/prometheus"
prometheus_web_external_url: "http://127.0.0.1:9090"
prometheus_config: "prometheus.yml"
prometheus_storage_retention_time: "60d"

install_blackbox_exporter: false
blackbox_exporter_version: 0.19.0
blackbox_exporter_config: "blackbox.yml"

install_alertmanager: false
alertmanager_version: 0.23.0
alertmanager_config: "alertmanager.yml"
# Must be absolute path
alertmanager_rules_config: "/etc/prometheus/alert_rules.yml"
alertmanager_web_external_url: "http://127.0.0.1:9093"
